//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUser
    {
        public SUser()
        {
            this.SApprovers = new HashSet<SApprover>();
            this.SUserRoles = new HashSet<SUserRole>();
            this.T_CA_Phase = new HashSet<T_CA_Phase>();
            this.T_LabourDevision_Ver = new HashSet<T_LabourDevision_Ver>();
            this.T_LabourDivision = new HashSet<T_LabourDivision>();
            this.T_LabourDivision1 = new HashSet<T_LabourDivision>();
            this.T_PhaseGroupDailyProduction = new HashSet<T_PhaseGroupDailyProduction>();
            this.T_LinePoDailyQuantities = new HashSet<T_LinePoDailyQuantities>();
            this.T_PhaseGroup_Phase = new HashSet<T_PhaseGroup_Phase>();
            this.T_UsingTechLog = new HashSet<T_UsingTechLog>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public bool IsOwner { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public bool IsLock { get; set; }
        public bool IsRequireChangePW { get; set; }
        public bool IsForgotPassword { get; set; }
        public string NoteForgotPassword { get; set; }
        public string Email { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
        public string Name { get; set; }
        public string WorkshopIds { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual ICollection<SApprover> SApprovers { get; set; }
        public virtual SCompany SCompany { get; set; }
        public virtual ICollection<SUserRole> SUserRoles { get; set; }
        public virtual ICollection<T_CA_Phase> T_CA_Phase { get; set; }
        public virtual ICollection<T_LabourDevision_Ver> T_LabourDevision_Ver { get; set; }
        public virtual ICollection<T_LabourDivision> T_LabourDivision { get; set; }
        public virtual ICollection<T_LabourDivision> T_LabourDivision1 { get; set; }
        public virtual ICollection<T_PhaseGroupDailyProduction> T_PhaseGroupDailyProduction { get; set; }
        public virtual ICollection<T_LinePoDailyQuantities> T_LinePoDailyQuantities { get; set; }
        public virtual ICollection<T_PhaseGroup_Phase> T_PhaseGroup_Phase { get; set; }
        public virtual ICollection<T_UsingTechLog> T_UsingTechLog { get; set; }
    }
}
