//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWorkerLevel
    {
        public SWorkerLevel()
        {
            this.T_CA_Phase = new HashSet<T_CA_Phase>();
            this.T_PhaseGroup_Phase = new HashSet<T_PhaseGroup_Phase>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Coefficient { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<T_CA_Phase> T_CA_Phase { get; set; }
        public virtual ICollection<T_PhaseGroup_Phase> T_PhaseGroup_Phase { get; set; }
    }
}
