//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CA_Phase_Mani
    {
        public int Id { get; set; }
        public int CA_PhaseId { get; set; }
        public int OrderIndex { get; set; }
        public Nullable<int> ManipulationId { get; set; }
        public string ManipulationCode { get; set; }
        public string ManipulationName { get; set; }
        public Nullable<double> TMUEquipment { get; set; }
        public Nullable<double> TMUManipulation { get; set; }
        public double Loop { get; set; }
        public double TotalTMU { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_ManipulationLibrary T_ManipulationLibrary { get; set; }
        public virtual T_CA_Phase T_CA_Phase { get; set; }
    }
}
