//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CA_Phase
    {
        public T_CA_Phase()
        {
            this.T_CA_Phase_Mani = new HashSet<T_CA_Phase_Mani>();
            this.T_CA_Phase_TimePrepare = new HashSet<T_CA_Phase_TimePrepare>();
            this.T_TechProcessVersionDetail = new HashSet<T_TechProcessVersionDetail>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public int WorkerLevelId { get; set; }
        public int PhaseGroupId { get; set; }
        public int ParentId { get; set; }
        public double TotalTMU { get; set; }
        public Nullable<int> ApplyPressuresId { get; set; }
        public double PercentWasteEquipment { get; set; }
        public double PercentWasteManipulation { get; set; }
        public double PercentWasteSpecial { get; set; }
        public double PercentWasteMaterial { get; set; }
        public string Node { get; set; }
        public string Video { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsLibrary { get; set; }
    
        public virtual SWorkerLevel SWorkerLevel { get; set; }
        public virtual ICollection<T_CA_Phase_Mani> T_CA_Phase_Mani { get; set; }
        public virtual T_CommodityAnalysis T_CommodityAnalysis { get; set; }
        public virtual T_Equipment T_Equipment { get; set; }
        public virtual ICollection<T_CA_Phase_TimePrepare> T_CA_Phase_TimePrepare { get; set; }
        public virtual ICollection<T_TechProcessVersionDetail> T_TechProcessVersionDetail { get; set; }
        public virtual T_PhaseGroup T_PhaseGroup { get; set; }
    }
}
