//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EquipTypeAttr_Default
    {
        public T_EquipTypeAttr_Default()
        {
            this.T_EquipmentTypeAttribute = new HashSet<T_EquipmentTypeAttribute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int EquipType_DefaultId { get; set; }
    
        public virtual ICollection<T_EquipmentTypeAttribute> T_EquipmentTypeAttribute { get; set; }
        public virtual T_EquipType_Default T_EquipType_Default { get; set; }
    }
}
