//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EquipmentType
    {
        public T_EquipmentType()
        {
            this.T_Equipment = new HashSet<T_Equipment>();
            this.T_EquipmentAttribute = new HashSet<T_EquipmentAttribute>();
            this.T_EquipmentTypeAttribute = new HashSet<T_EquipmentTypeAttribute>();
            this.T_ManipulationLibrary = new HashSet<T_ManipulationLibrary>();
            this.T_ManipulationLibrary1 = new HashSet<T_ManipulationLibrary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipTypeDefaultId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<T_Equipment> T_Equipment { get; set; }
        public virtual ICollection<T_EquipmentAttribute> T_EquipmentAttribute { get; set; }
        public virtual T_EquipType_Default T_EquipType_Default { get; set; }
        public virtual ICollection<T_EquipmentTypeAttribute> T_EquipmentTypeAttribute { get; set; }
        public virtual ICollection<T_ManipulationLibrary> T_ManipulationLibrary { get; set; }
        public virtual ICollection<T_ManipulationLibrary> T_ManipulationLibrary1 { get; set; }
    }
}
