//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LabourDivision
    {
        public T_LabourDivision()
        {
            this.T_LabourDevision_Ver = new HashSet<T_LabourDevision_Ver>();
            this.T_LinePoDailyQuantities = new HashSet<T_LinePoDailyQuantities>();
        }
    
        public int Id { get; set; }
        public int TechProVer_Id { get; set; }
        public int ParentId { get; set; }
        public int LineId { get; set; }
        public int TotalPosition { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_Line T_Line { get; set; }
        public virtual T_TechProcessVersion T_TechProcessVersion { get; set; }
        public virtual ICollection<T_LabourDevision_Ver> T_LabourDevision_Ver { get; set; }
        public virtual ICollection<T_LinePoDailyQuantities> T_LinePoDailyQuantities { get; set; }
        public virtual SUser SUser { get; set; }
        public virtual SUser SUser1 { get; set; }
        public virtual T_CommodityAnalysis T_CommodityAnalysis { get; set; }
    }
}
