//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LabourDevision_Ver
    {
        public T_LabourDevision_Ver()
        {
            this.T_LinePosition = new HashSet<T_LinePosition>();
            this.T_LinePoDailyQuantities = new HashSet<T_LinePoDailyQuantities>();
            this.T_UsingTechLog = new HashSet<T_UsingTechLog>();
        }
    
        public int Id { get; set; }
        public int LabourDivisionId { get; set; }
        public int TotalPosition { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_LabourDivision T_LabourDivision { get; set; }
        public virtual ICollection<T_LinePosition> T_LinePosition { get; set; }
        public virtual SUser SUser { get; set; }
        public virtual ICollection<T_LinePoDailyQuantities> T_LinePoDailyQuantities { get; set; }
        public virtual ICollection<T_UsingTechLog> T_UsingTechLog { get; set; }
    }
}
