//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LinePosition
    {
        public T_LinePosition()
        {
            this.T_LinePositionDetail = new HashSet<T_LinePositionDetail>();
        }
    
        public int Id { get; set; }
        public int LabourDivisionId { get; set; }
        public int OrderIndex { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public bool IsHasBTP { get; set; }
        public bool IsHasExitLine { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_LabourDivision T_LabourDivision { get; set; }
        public virtual ICollection<T_LinePositionDetail> T_LinePositionDetail { get; set; }
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
