//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManipulationLibrary
    {
        public T_ManipulationLibrary()
        {
            this.T_CA_Phase_Mani = new HashSet<T_CA_Phase_Mani>();
            this.T_ManipulationEquipment = new HashSet<T_ManipulationEquipment>();
            this.T_ManipulationFile = new HashSet<T_ManipulationFile>();
        }
    
        public int Id { get; set; }
        public int ManipulationTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double StandardTMU { get; set; }
        public double UserTMU { get; set; }
        public Nullable<int> EquipmentTypeId { get; set; }
        public Nullable<int> StopPrecisionId { get; set; }
        public Nullable<int> ApplyPressureId { get; set; }
        public Nullable<int> NatureCutsId { get; set; }
        public Nullable<double> Distance { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_ApplyPressureLibrary T_ApplyPressureLibrary { get; set; }
        public virtual ICollection<T_CA_Phase_Mani> T_CA_Phase_Mani { get; set; }
        public virtual ICollection<T_ManipulationEquipment> T_ManipulationEquipment { get; set; }
        public virtual ICollection<T_ManipulationFile> T_ManipulationFile { get; set; }
        public virtual T_ManipulationTypeLibrary T_ManipulationTypeLibrary { get; set; }
        public virtual T_ManipulationTypeLibrary T_ManipulationTypeLibrary1 { get; set; }
        public virtual T_NatureCutsLibrary T_NatureCutsLibrary { get; set; }
        public virtual T_StopPrecisionLibrary T_StopPrecisionLibrary { get; set; }
        public virtual T_EquipmentType T_EquipmentType { get; set; }
        public virtual T_EquipmentType T_EquipmentType1 { get; set; }
    }
}
