//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManipulationEquipment
    {
        public int Id { get; set; }
        public int ManipulationId { get; set; }
        public int EquipmentId { get; set; }
        public double UserTMU { get; set; }
        public double MachineTMU { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_ManipulationLibrary T_ManipulationLibrary { get; set; }
        public virtual T_Equipment T_Equipment { get; set; }
    }
}
