//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PhaseGroupDailyProduction
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int ComAnaId { get; set; }
        public int PhaseGroupId { get; set; }
        public int ComandType { get; set; }
        public int Quantities { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual T_PhaseGroup T_PhaseGroup { get; set; }
        public virtual SUser SUser { get; set; }
        public virtual T_CommodityAnalysis T_CommodityAnalysis { get; set; }
    }
}
