//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TechProcessVersionDetail
    {
        public T_TechProcessVersionDetail()
        {
            this.T_LinePositionDetail = new HashSet<T_LinePositionDetail>();
        }
    
        public int Id { get; set; }
        public int TechProcessVersionId { get; set; }
        public int CA_PhaseId { get; set; }
        public double StandardTMU { get; set; }
        public double Percent { get; set; }
        public double TimeByPercent { get; set; }
        public double Worker { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual T_CA_Phase T_CA_Phase { get; set; }
        public virtual ICollection<T_LinePositionDetail> T_LinePositionDetail { get; set; }
        public virtual T_TechProcessVersion T_TechProcessVersion { get; set; }
    }
}
