//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TechProcessVersion
    {
        public T_TechProcessVersion()
        {
            this.T_LabourDivision = new HashSet<T_LabourDivision>();
            this.T_TechProcessVersionDetail = new HashSet<T_TechProcessVersionDetail>();
            this.T_UsingTechLog = new HashSet<T_UsingTechLog>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ParentId { get; set; }
        public double TimeCompletePerCommo { get; set; }
        public int NumberOfWorkers { get; set; }
        public double WorkingTimePerDay { get; set; }
        public double PacedProduction { get; set; }
        public double ProOfGroupPerHour { get; set; }
        public double ProOfGroupPerDay { get; set; }
        public double ProOfPersonPerDay { get; set; }
        public double PricePerMinute { get; set; }
        public double PricePerSecond { get; set; }
        public double Allowance { get; set; }
        public int PercentWorker { get; set; }
        public int Percent { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<T_LabourDivision> T_LabourDivision { get; set; }
        public virtual ICollection<T_TechProcessVersionDetail> T_TechProcessVersionDetail { get; set; }
        public virtual ICollection<T_UsingTechLog> T_UsingTechLog { get; set; }
        public virtual T_Product T_Product { get; set; }
    }
}
