//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UsingTech_Detail
    {
        public int Id { get; set; }
        public int UsingTechLogId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual T_UsingTechLog T_UsingTechLog { get; set; }
    }
}
