//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRO_IED_A.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkShop
    {
        public T_WorkShop()
        {
            this.T_Line = new HashSet<T_Line>();
            this.HR_Employee = new HashSet<HR_Employee>();
            this.T_CA_Phase = new HashSet<T_CA_Phase>();
            this.T_UsingTechLog = new HashSet<T_UsingTechLog>();
            this.SUsers = new HashSet<SUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<T_Line> T_Line { get; set; }
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
        public virtual ICollection<T_CA_Phase> T_CA_Phase { get; set; }
        public virtual ICollection<T_UsingTechLog> T_UsingTechLog { get; set; }
        public virtual ICollection<SUser> SUsers { get; set; }
    }
}
